name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  build:
    name: Build Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME#refs/tags/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          BRANCH_NAME=${BRANCH_NAME//_/-}
          echo "BRANCH_NAME=$(echo $BRANCH_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=$BRANCH_NAME" >> $GITHUB_ENV
          fi
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: virtualflybrain/flylightlarvaldata:${{ env.DOCKER_TAG }}